# FIXME: generic travis yaml for testing
language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: python /dragonchain/util/thrift_conversions.py

# FIXME: restricting to this branch for testing purposes
branches:
  only:
    - travis-ci