language: python
python:
  - "2.7"
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script:
  - python blockchain/*.py
  - python blockchain/util/*.py

# FIXME: restricting to this branch for testing purposes
branches:
  only:
    - travis-ci